### ISSUE TITLE
License

### ISSUE THREAD

**Issue by krfkeith** [weshoke/DSL#1]
Hi!

This project looks really awesome, but I don't see any license information? Would you mind specifying what license the code itself is under, and what restrictions, if any, the output is under?

Thanks!

**Comment by krfkeith** [comment]
Hi!

This project looks really awesome, but I don't see any license information? Would you mind specifying what license the code itself is under, and what restrictions, if any, the output is under?

Thanks!

**Comment by weshoke** [comment]
I added the LICENSE file.  It's MIT.

**Comment by krfkeith** [comment]
Awesome thanks, I just wanted to clarify.
