### ISSUE TITLE
Output Dependencies

### ISSUE THREAD

**Issue by krfkeith** [weshoke/DSL#2]
Hello,

I was just curious if the outputed code has any dependencies, or whether it can stand on its own?

Thanks

**Comment by weshoke** [comment]
The output is a parser object.  The only dependency for the library is LPEG.

**Comment by krfkeith** [comment]
So does the output parser object depend on LPEG?

**Comment by weshoke** [comment]
The output of the parser is an AST.  It's a tree of rules and tokens.  There are no dependencies on any libs.  To do something useful with it, you have to write an interpreter.

**Comment by krfkeith** [comment]
Okay, that makes sense.
